#!/usr/bin/env python3
"""Generate client/offsets_table.inc from client/offsets.hpp.

offsets.hpp stays the human-readable source of truth: one variable per game-specific number, with the
comment that says how it was found. This script lists those variables so the DLL can set them by name
from a per-build JSON file (client/offsets_json.hpp) and so the derivation pipeline knows the full set
of keys a build file must answer for.

    python tools/update/gen_offset_table.py            # rewrite client/offsets_table.inc
    python tools/update/gen_offset_table.py --json     # print the key list as JSON (for the pipeline)
    python tools/update/gen_offset_table.py --check    # exit 1 if the .inc is stale
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HPP = os.path.join(ROOT, "client", "offsets.hpp")
INC = os.path.join(ROOT, "client", "offsets_table.inc")

DECL = re.compile(r"^inline\s+(std::uintptr_t|std::int32_t|int)\s+(\w+)\s*=\s*([^;]+);", re.M)


def parse():
    text = open(HPP, encoding="utf-8").read()
    out = []
    for m in DECL.finditer(text):
        typ, name, value = m.group(1), m.group(2), m.group(3).strip()
        kind = "uintptr" if typ == "std::uintptr_t" else "int"
        out.append({"name": name, "type": kind, "default": value})
    return out


def render(entries):
    lines = ["// GENERATED by tools/update/gen_offset_table.py from client/offsets.hpp -- do not edit.",
             "// One line per offset variable: OXC_OFFSET(kind, NAME). Included by client/offsets_json.hpp",
             "// to map JSON keys onto the variables, in offsets.hpp order.", ""]
    for e in entries:
        lines.append(f"OXC_OFFSET({e['type']}, {e['name']})")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    entries = parse()
    if a.json:
        print(json.dumps(entries, indent=2))
        return
    text = render(entries)
    if a.check:
        cur = open(INC, encoding="utf-8").read() if os.path.exists(INC) else ""
        if cur != text:
            print("client/offsets_table.inc is stale: run python tools/update/gen_offset_table.py", file=sys.stderr)
            sys.exit(1)
        print("offsets_table.inc is current")
        return
    with open(INC, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote client/offsets_table.inc ({len(entries)} offsets)")


if __name__ == "__main__":
    main()
